### ISSUE TITLE
[Crash]: Rendering golden bundle, crashes client.

### ISSUE THREAD

**Issue by WimpieRatte** [Fuzss/metalbundles#6]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

Giving the full details of how we recreated the issue.

1. We were playing this modpack: https://modrinth.com/modpack/colonies-and-technologies
2. I invited my friend through the Essential mod interface into my single player world.
3. I crafted a golden bundle and left it in a barrel for him.
4. When he opened the barrel, his client crashed.
5. After logging back in, I tried throwing him the bundle instead, but his client crashed immediately again.

_For a quick preview:_
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?] {re:mixin}
	at fuzs.metalbundles.world.item.MetalBundleItem.getContentWeight(MetalBundleItem.java:91) ~[MetalBundles-v8.0.0-1.20.1-Forge.jar%23532!/:8.0.0] {re:classloading}
	at fuzs.metalbundles.client.MetalBundlesClient.lambda$onRegisterItemModelProperties$0(MetalBundlesClient.java:14) ~[MetalBundles-v8.0.0-1.20.1-Forge.jar%23532!/:8.0.0] {re:classloading}
	at net.minecraft.client.renderer.item.ClampedItemPropertyFunction.m_141951_(ClampedItemPropertyFunction.java:14) ~[client-1.20.1-20230612.114412-srg.jar%23634!/:?] {re:classloading}
	at net.minecraft.client.renderer.block.model.ItemOverrides.redirect$zhk000$fixCrashWithNullWorld(ItemOverrides.java:533) ~[client-1.20.1-20230612.114412-srg.jar%23634!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:litematica.mixins.json:MixinModelOverrideList,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.model.ItemOverrides.m_173464_(ItemOverrides.java:87) ~[client-1.20.1-20230612.114412-srg.jar%23634!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:litematica.mixins.json:MixinModelOverrideList,pl:mixin:A,pl:runtimedistcleaner:A}

### Crash Report (Required)
(The first 2 files in this link was when he opened the barrel and the last one was when I tried throwing the item to him.)

https://gist.github.com/WimpieRatte/49c2cb517d2ab0e4caab7eafdf7d1685

### latest.log (Optional)

https://gist.github.com/WimpieRatte/27d1f1c8f0f0189d6939b4c9fb3d5f89

**Comment by Fuzss** [comment]
Metal bundles use "providers" for the interaction logic, which are controlled by the server and are synced to clients on login.
In this case the bundle interaction logic provider was not found on the client of your friend.

I assume something related to provider syncing isn't working correctly here, maybe due to the way essentials world sharing works (I think it uses something similar to lan play which can sometimes cause issues).

Need to investigate this further, no clue right now unfortunately.

**Comment by WimpieRatte** [comment]
Thanks for the feedback!
At least we have bags of holding until there's new news. :D

**Comment by Fuzss** [comment]
Seems to be related to https://github.com/Fuzss/easyshulkerboxes/issues/33.

**Comment by UltraToon** [comment]
I have the same issue @Fuzss but as in hosting LAN worlds with e4mc.

**Comment by Fuzss** [comment]
This should be fixed in v8.0.1 and in the 1.20.4 port. Please reopen if it’s not.
